# Generated by Django 3.1.5 on 2021-11-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='idade_minina',
            new_name='idade_minima',
        ),
    ]
