# Generated by Django 3.1.5 on 2021-11-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_auto_20211126_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'permissions': [('pode_ver_estatisticas', 'Pode ver estatísticas')]},
        ),
    ]
