# Generated by Django 3.1.5 on 2021-11-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20211126_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='id',
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='codigo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
